name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build package
        run:  |
          python -m pip install dist/app-0.2.tar.gz
      - name: Run pytest
        run: |
          pytest test_func.py --cov=your_script --cov-report=xml 
      - name: Run PySpark Application
        run: |
          python main.py datasets/dataset_one.csv datasets/dataset_two.csv datasets/dataset_three.csv